### ISSUE TITLE
Update User Manual

### ISSUE THREAD

**Issue by Nexxado** [Nexxado/ProjectHands#11]
# [User Manual](https://github.com/Nexxado/ProjectHands/wiki/User-Manual)

View [Instructions](http://jce-il.github.io/se-class16b/morea/planning/experience-project5-zfr.html#section-5)

**Comment by Nexxado** [comment]
Added instructions on [how to run the server locally](https://github.com/Nexxado/ProjectHands/wiki/User-Manual#1-how-to-run-the-server-locally)

**Comment by ihabZhaika** [comment]
completed the basic User manual infromation
