### ISSUE TITLE
Sign-Up & Login System [Backend]

### ISSUE THREAD

**Issue by Nexxado** [Nexxado/ProjectHands#21]
Sign-Up
- [x] Send Sign-up form to admin
- [x] Send Confirmation Email
- [x] Send Account activation after admin approval  
- [x] Assign Role to user (permissions)

Login
- [x] Lookup user in database & respond accordingly

**Comment by ihabZhaika** [comment]
considering use auth0 as better solution than cookies and more secure

**Comment by Nexxado** [comment]
Changed login system to use [Json Web Token](https://jwt.io/) and HttpOnly cookies.
Signup now requires email confirmation to activate the account or it is deleted in 24 hours.

**Comment by ihabZhaika** [comment]
changed to bcrypt

**Comment by Nexxado** [comment]
backend signup and login uses PassportJS library
