### ISSUE TITLE
ZFR

### ISSUE THREAD

**Issue by Nexxado** [Nexxado/ProjectHands#27]
# [Iteration 0 - ZFR](https://github.com/Nexxado/ProjectHands/wiki/Iteration-0)
# [Iteration 1 - MVP](https://github.com/Nexxado/ProjectHands/wiki/Iteration-1)

**Comment by Nexxado** [comment]
updated [Iteration 0 - ZFR](https://github.com/Nexxado/ProjectHands/wiki/Iteration-0) based on review

**Comment by robi-y** [comment]
I can't assign myself nor close the issue, anyhow some more comments:
Stories on ZFR page are fine but redundant  - just manage the backlog in the issues.
Planning - no sturies/issues assigned to next milestones in the issue system
Prototype description is fine
Iteration 1: needs more focus target
Estimation: excellent, I hope you can make it.
Goodluck

**Comment by Nexxado** [comment]
for some reason u weren't listed as a collaborator, its fixed now.

I deleted the ZFR User Stories
Further detailed Iteration 1 Goal

About Planning, i thought we're planning each iteration at the end of the previous one.
I think assigning issues to the next iteration milestone is the same as planning it and seem redundant to do it a long time before we even consider what that iteration goal is.

**Comment by robi-y** [comment]
We just want a general plan concerning for each story a target iteration

**Comment by Nexxado** [comment]
All issues are now assigned to a milestone.

**Comment by robi-y** [comment]
:+1:
