### ISSUE TITLE
project3-srs-submission

### ISSUE THREAD

**Issue by ihabZhaika** [Nexxado/ProjectHands#3]
Link to the srs 
https://github.com/Nexxado/ProjectHands/wiki/SRS
This submission is for all the team members

**Comment by Nexxado** [comment]
### Changes made after Lecturer's review:

1. Updated Use-Cases' scenario names easier to understand 
2. Updated "Volunteer-Signup" Use-case "major success" - Added more details to the steps

Thank you.

**Comment by ItamarShDev** [comment]
:+1:
