### ISSUE TITLE
Picture Upload and Share

### ISSUE THREAD

**Issue by Nexxado** [Nexxado/ProjectHands#37]
- [x] Upload pictures per renovation
- [x] Share selected pictures (by Admin) on Home Page

**Comment by Nexxado** [comment]
one options is using Base64 to store the images

**Comment by ItamarShDev** [comment]
Dont Use Base64
Its a nice option when dealing with icons and thumbnails
Its not recommended for big pictures, and not even storage wise

Which ever Db you're using, I'm sure you can store Files or Document for pictures.

Also' dont be afraid to check some picture storing services, even Google Drive.
