### ISSUE TITLE
iteration 1 review

### ISSUE THREAD

**Issue by Nexxado** [Nexxado/ProjectHands#38]
#  [Wiki page](https://github.com/Nexxado/ProjectHands/wiki/Iteration-1)

**Comment by ItamarShDev** [comment]
please add a paragraph explaining of the class materials you've covered up (testing etc)

**Comment by Nexxado** [comment]
do u mean like unit testing, mongodb, express, nodejs ?

**Comment by ihabZhaika** [comment]
you can check Developers Manual - > test

**Comment by ItamarShDev** [comment]
:+1:

**Comment by ItamarShDev** [comment]
oops...
cant find your [code reviews](http://jce-il.github.io/se-class16b/morea/planning/experience-project6-iterations.html#section-14)

**Comment by Nexxado** [comment]
@DDraiman1990 @ihabZhaika @RubyLichtenstein Do a code review for at least one team member, regarding to iteration 1.

**Comment by ItamarShDev** [comment]
@Nexxado yeah, also add link to it in iteration page next to your name

**Comment by Nexxado** [comment]
@ItamarShDev 
### [Code Review](https://github.com/Nexxado/ProjectHands/wiki/Iteration-1#code-review)

**Comment by ihabZhaika** [comment]
In the excel file we have 100 so to be closed
