### ISSUE TITLE
SRS - Modifications after first SRS Review

### ISSUE THREAD

**Issue by DDraiman1990** [Nexxado/ProjectHands#4]
### Use-Case:
1. Use-Case 1: Signup. only says "User Signup" while user is always a volunteer and thus it requires more information.
2. Diagram: shows volunteer and Team Manager as seperate Actors while Team Manager suppose to inherit from Volunteer
3. Use-Case 2: New Project means Renovation Project.
4. Use-Case 2: "Fill Form" needs details and examples as to what parameters it refers to.

**Comment by Nexxado** [comment]
Done.
