### ISSUE TITLE
Dashboard and Chat

### ISSUE THREAD

**Issue by RubyLichtenstein** [Nexxado/ProjectHands#47]
In the css files use  :root Selector for global values 
>:root { 
    --global-height: 10px;
    --global-width:   10px;
    --global-color:  #2196F3;
}
.a{
   height: var(--global-height);
   width:   var(--global-width);
   color:   var(--global-color);
}

**Comment by Nexxado** [comment]
css attributes written on the body/html tags will be inherited by all its child divs etc.
when needed, overriding those values considering [CSS Specificity](https://css-tricks.com/specifics-on-css-specificity/)
