### ISSUE TITLE
SDS Document

### ISSUE THREAD

**Issue by Nexxado** [Nexxado/ProjectHands#5]
Finished [SDS document](https://github.com/Nexxado/ProjectHands/wiki/SDS)

**Comment by robi-y** [comment]
Review:
- [ ] Missing risks to capabilities
- [x] explain diagrams rational

- nice test plan

**Comment by DDraiman1990** [comment]
finished adding risks to capabilities

**Comment by robi-y** [comment]
I'm writing here a detailed review:
### SDS Page
- well organised (:+1: for the table of content)
- excellent document goal
- Capabilities list (originally was not connected to risks - corrected)
- links to updated risk plan (I see it was updated), user manual (headers are just fine for now), review summary (please add a section what you fixed following the oral and written review and update in this issue comments) 

- Diagrams
  - use of official UML diagrams :+1: 
  - excellent explanations of diagram purpose, considerataios and risks.
  - class diagram: nice use of multiplicities on class relations
  - state diagram: I'm not sure it is so interesting, we dicussed on class allready
  - sequence diagram (actually one behaviral diagram is enough): I prefer describing more uniqe scenarios than login and register (and you explained that you have a uniqe registration process)

- Sections
  - Persistent: many times it is good to add a diagram for the DB tables (e.g. ERD)
  - non-functional requirements: the first two are really parts of the functional ones.
  - :100: : for starting a test plan (although it was optional), it is 

- Review Summary
  - please complete and let us know when ready

Excellent work! keep it

**Comment by ihabZhaika** [comment]
> sequence diagram (actually one behaviral diagram is enough): I prefer describing more uniqe scenarios than login and register (and you explained that you have a uniqe registration process)

Added new sequence diagram that describes main use case

**Comment by robi-y** [comment]
:+1:

**Comment by RubyLichtenstein** [comment]
> * Sections
   * Persistent: many times it is good to add a diagram for the DB tables (e.g. ERD)
   * non-functional requirements: the first two are really parts of the functional ones.

**Non functional requirements**
*  updated first two non-functional requirements

**Persistent**
*  added collection diagram for our mongoDb

**Comment by robi-y** [comment]
:100:

On Thu, Mar 31, 2016 at 11:01 AM, RubyLichtenstein <notifications@github.com

**Comment by Nexxado** [comment]
added review summary

**Comment by robi-y** [comment]
:+1:
