### ISSUE TITLE
unable to see the bottom wedgets dashbaord , renovation pages

### ISSUE THREAD

**Issue by ihabZhaika** [Nexxado/ProjectHands#53]
### Description
when open the renovation page , only the upper part of the map is visible
when add wedgets the the dashboard , only the top wedigets are visiple to the user
### what to be done
- [ ] add vertical silder

**Comment by Nexxado** [comment]
there is a vertical slider, can u please provide screenshots?

**Comment by ihabZhaika** [comment]
maybe it was extreme case ? now every thing is good 
i will close it and if i face it again i will record it
