### ISSUE TITLE
Create Statistics API

### ISSUE THREAD

**Issue by Nexxado** [Nexxado/ProjectHands#61]
- [x] Total volunteering hours for each month in each year [from renovations]
- [x] Total money spent for each month in each year  [ from renovations]
- [x] Volunteers number for each month in each year [from renovations]
- [x] Volunteers number for each month in each year [from users]
- [x] Number of renovations for each month in each year 
- [x] Create Statistics endpoints

**Comment by Nexxado** [comment]
@ihabZhaika Please list here the different statistics needed, as instructed by client.

**Comment by ihabZhaika** [comment]
Example :
http://localhost:8080/api/statistics/renovationsPerDate/%7B%22yearFrom%22:2016,%22yearTo%22:2016,%22monthFrom%22:6,%22monthTo%22:6,%22dayFrom%22:1,%22dayTo%22:30%7D
