### ISSUE TITLE
Iteration 4 review

### ISSUE THREAD

**Issue by Nexxado** [Nexxado/ProjectHands#62]
[Wiki page](https://github.com/Nexxado/ProjectHands/wiki/Iteration-4)

**Comment by ItamarShDev** [comment]
missing code reviews and some more details in the summary
elaborate on how well was the iteration in term of the success/failure
from example: i saw you didnt completed your points due to client meeting. what about elaborating on how and why did you pass on some tasks and did others?

**Comment by Nexxado** [comment]
@ItamarShDev 

added more details to [iteration conclusion](https://github.com/Nexxado/ProjectHands/wiki/Iteration-4#iteration-conclusion)
doing code reviews

**Comment by Nexxado** [comment]
@ItamarShDev [Code Reviews](https://github.com/Nexxado/ProjectHands/wiki/Iteration-4#code-review)

**Comment by ItamarShDev** [comment]
:+1:
