### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by RubyLichtenstein** [Nexxado/ProjectHands#70]
https://github.com/Nexxado/ProjectHands/blob/statistics_api/server/routes/user.js#L53

**Comment by Nexxado** [comment]
@RubyLichtenstein 
dead link, please update

**Comment by RubyLichtenstein** [comment]
https://github.com/Nexxado/ProjectHands/blob/dev/server/routes/user.js#L53

**Comment by Nexxado** [comment]
wheres the typo?

**Comment by RubyLichtenstein** [comment]
line 53

**Comment by Nexxado** [comment]
whats the typo ><

**Comment by RubyLichtenstein** [comment]
aLL_signups

**Comment by Nexxado** [comment]
kk got it
