### ISSUE TITLE
Front end statistics service missing Doc 

### ISSUE THREAD

**Issue by RubyLichtenstein** [Nexxado/ProjectHands#77]
Please write doc of the function arguments format

**Comment by ihabZhaika** [comment]
All the functions of the statistics api takes this input
year , month , dayFrom , dayTo

Return:
an object like this [ depend on which function lets say volunteering hours in renovations ] 
{
renovation1 : 15 ,
mySweetRreno : 30,
........
,
totalHourse :45

}
for further info go statistics.js in server everethod have documentation , if it not enough tell me so i write a doc for it

**Comment by RubyLichtenstein** [comment]
Year: 0-9999
Month: 1-12
Day: 1-31 
?

**Comment by ihabZhaika** [comment]
ya

**Comment by RubyLichtenstein** [comment]
v

**Comment by ihabZhaika** [comment]
ok cool
