### ISSUE TITLE
Advanced Chat Features - Error in code.

### ISSUE THREAD

**Issue by DDraiman1990** [Nexxado/ProjectHands#78]
- [x] Fix error with GetChatHistory in chatRoomController

### Description
im getting an Error when i enter a renovation page. 
### Steps to Reproduce
1. Go to Renovations -> pick a renovation -> open Console
2. You will see a red message with an error about forEach in getChatHistory.

### Screenshot

[The Error Message](http://prntscr.com/bdrjpo)
[The code with the error](http://prntscr.com/bdrk1w)

**Comment by Nexxado** [comment]
fixed, pushed to dev branch.
