### ISSUE TITLE
Home page bugs

### ISSUE THREAD

**Issue by ndraiman** [Nexxado/ProjectHands#93]
- [x] Don't stretch photos in image slider
- [x] home page content is misaligned
- [ ] Update home page statistics to hold real information
- [x] Update home page Staff roles with real information - contact client to get the data
- [x] Add organization ads as appear on the organization [Facebook page](https://www.facebook.com/%D7%A4%D7%A8%D7%95%D7%99%D7%A7%D7%98-%D7%99%D7%93%D7%99%D7%99%D7%9D-1498261200461010)

**Comment by Nexxado** [comment]
did the first 2 for you, in website_styles branch
please update it to hold real info
